name:                swiss-army-knife-hs
version:             0.0.1.0
github:              "flajann2/swiss-army-knife-hs"
license:             MIT
author:              "Fred Mitchell"
maintainer:          "fred.mitchell@atomlogik.de"
copyright:           "2024 Fred Mitchell & Atomlogik"

extra-source-files:
- README.org
- ChangeLog.org

description:         Please see the README on GitHub at <https://github.com/githubuser/swiss-army-knife-hs#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: lib
  ghc-options:
    - -O3
    - -Wall
  dependencies:
    - optparse-applicative
    - http-conduit
    - aeson
    - bytestring
    - process
    - split
    - yaml
    - yaml-combinators
    
executables:
  sak:
    main:                SwissArmyKnife.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - swiss-army-knife-hs
      - optparse-applicative

tests:
  swiss-army-knife-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - swiss-army-knife-hs

