* swiss-army-knife-hs
  A collection of powerful but usefuli small tools.
  Written in Haskell, the most powerful language on
  the planet.

  Currently, only Arch is supported, BTW. I am open to pull requests for
  other distros. There are a lot of subtle differences and I don't 
  have the time to support everything.

** Created By
   Fred Mitchell & Atomlogik

** Versions
   + 0.0.0.2 - bug fixes
   + 0.0.1.1 - new feature
   + 0.1.0.3 - 2 new feature, internally invokes sudo,
      adopted "standard" for 4 number versioning X.Y.Z.W:

      | # | Description                                   |
      |---+-----------------------------------------------|
      | X | Major version (breaking changes)              |
      | Y | Minor version (new features)                  |
      | Z | Patch version (bug fixes)                     |
      | W | Build or revision number (specific iteration) |

      So from now on, this will be applied.
   + 0.1.0.4 - fix for install issues with 0.1.0.3
      
** Introduction
   Swiss-Army-Knife is a collection of useful
   tools that you can do quickly.

   Currently, only Arch linux is supported. I am open to pull requests
   to support other distros. 

** Documentation
   These are the current "knives" implemented. More to come. Open
   to suggestions.
   + Note that you no longer have to prepend "sudo" to do system-level
      operations.
*** sak --help
    Will list all the current commands.
*** sak extip
    Will tell you what your external IP is for your connection,
    either in IPv4 or IPv6 Useful if you use a VPN
*** sak kernel
    Will tell you the version of the installed kernel as well
    as the running version.
*** sak sleep
    Will put your system in standby mode.
*** sak zfscheck
    If you use the zfs from archzfs, sometimes it 
    does not keep up with the latest kernel release.
    Check to see the latest kernel zfs supports before
    you do a system upgrade.
*** sak wg
    If you use WireGuard for your VPN, manage it from
    here. List your installed WireGuard options,
    and swap among them. you can start, stop, and list your
    WireGuard VPNs.
*** sak nm
    Manage NetworkManager
*** sak sn
    Manage systemd-networkd

** Examples
   + sak extip
     Will list your external IP and location information
   + sak wg -l
     (If you are using wg_quick) will list all of your available WG vpns.
     
