#!/usr/bin/env bash

meta_url='https://raw.githubusercontent.com/openzfs/zfs/master/META'
target_version=$(pacman -Si linux | awk '/^Version/ { print $3 }')
compat_version=$(curl -sSL "$meta_url" | awk '$1 == "Linux-Maximum:" { print $2 }')

if [[ $(printf '%s\n%s' "$target_version" "$compat_version" | sort -V | head -n1) != "$target_version" ]]; then
    echo "Aborting: $target_version is newer than the OpenZFS Linux-Maximum version $compat_version"
    exit 1
fi
